import type { Metadata } from 'next'

import './globals.css'
import { Onest } from 'next/font/google'
import { Header } from '@/components'
const inter = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#151a36] text-gray-800 ${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
